version: '2'
services:
    proxy:
        build:
            context: ./docker/nginx 
        depends_on:
            - api
        ports: 
            - "443:443"
    api:
        build: .
        env_file: ./.env
        depends_on:
            - db
    db:
        build:
            context: ./docker/postgres