version: '2'

volumes: 
    # Create a volume in the host system to persist postgres data
    pgdata: {}

services:
    proxy:
        build:
            context: ./nginx 
        depends_on:
            - api
        ports: 
            - "443:443"
    auth:
        build:
            context: ./parrot-auth
        env_file: ./parrot-auth/.env
        depends_on:
            - db
    api:
        build:
            context: ./parrot-api
        env_file: ./parrot-api/.env
        depends_on:
            - db
            - auth
    db:
        ports:
            - "5432:5432"
        build:
            context: ./postgres
        volumes:
            # Use the pgdata volume to persist this db
            - pgdata:/var/lib/postgresql/data/pgdata
